version: "3.3"
services:
  app:
    container_name: student-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      FLASK_APP: app/app.py
      FLASK_RUN_HOST: 0.0.0.0
  
  app2:
    container_name: student-api-2
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      FLASK_APP: app/app.py
      FLASK_RUN_HOST: 0.0.0.0
      
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students
    ports:
      - "3306:3306"